<a href="https://colab.research.google.com/github/dhairyaostwal/CSE4020-Codes/blob/main/Try/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the required libraries
import pandas as pd, numpy as np
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

In [37]:
dataset = pd.read_csv('cancer-data-manipulated - cancer-data.csv')

X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [38]:
dataset

avg_cyt_re  avg_cyt_gr  avg_cyt_bl Diagnosis
0  130.713275  123.667915  145.271328         M
1  115.975610   67.243902  140.126016         B
2  135.955693  129.935312  144.863093         M
3  131.139544  122.655338  143.148741         M
4  150.808105  142.667461  176.097735         M
5  130.945142   91.728024  147.307336         B
6   90.649587   58.960331   96.546006         B
7  132.686975  126.090336  151.857143         M
8  143.154220  131.805585  163.624921         M
9  126.637787  112.096381  143.146486         B

In [15]:
for i in range(len(y)):
  if(y[i] == 'M'):
    y[i] = 1
  else:
    y[i] = 0

In [16]:
y

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 0], dtype=object)

In [4]:
dataset.describe()

avg_cyt_re  avg_cyt_gr  avg_cyt_bl
count   10.000000   10.000000   10.000000
mean   128.866594  110.685058  145.198880
std     16.312907   28.504639   20.397183
min     90.649587   58.960331   96.546006
25%    127.656659   96.820113  143.147050
50%    131.042343  123.161626  145.067210
75%    135.138513  128.974068  150.719691
max    150.808105  142.667461  176.097735

## Splitting into 70:30 ratio

In [39]:
# now lets split the data into train and test
from sklearn.model_selection import train_test_split

# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((7, 1), (3, 1))

In [40]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5,
                                       n_estimators=100, oob_score=True)

classifier_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [41]:
# checking the oob score
classifier_rf.oob_score_

0.7142857142857143

In [19]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train);

In [20]:
# Use the forest's predict method on the test data
predictions = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(predictions - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.44 degrees.


In [25]:
y_test

array([1, 0, 0], dtype=object)

In [26]:
errors

array([0.0, 0.347, 0.985], dtype=object)

In [30]:
# Labels are the values we want to predict
labels = np.array(dataset['Diagnosis'])
# Remove the labels from the dataset
# axis 1 refers to the columns
dataset= dataset.drop('Diagnosis', axis = 1)
# Saving feature names for later use
feature_list = list(dataset.columns)

In [32]:
feature_list

['avg_cyt_re', 'avg_cyt_gr', 'avg_cyt_bl']

In [31]:
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Import tools needed for visualization
from sklearn.tree import export_graphviz
import pydot
# Pull out one tree from the forest
tree = rf.estimators_[5]
# Export the image to a dot file
export_graphviz(tree, out_file = 'tree.dot', feature_names = feature_list, rounded = True, precision = 1)
# Use dot file to create a graph
(graph, ) = pydot.graph_from_dot_file('tree.dot')
# Write graph to a png file
graph.write_png('tree.png')

ValueError: ignored

In [24]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%')

NameError: ignored

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import plot_tree
plt.figure(figsize=(80,40))
plot_tree(rf_best.estimators_[5], feature_names = X.columns,class_names=['Cancer', "Not Cancer"],filled=True);


NameError: ignored

<Figure size 5760x2880 with 0 Axes>

In [42]:
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier

In [45]:
cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1)

# evaluate the model and collect the results
scores = cross_val_score(classifier_rf, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
scores

array([0.5       , 0.66666667, 0.66666667, 0.75      , 0.66666667,
       0.33333333, 0.75      , 0.33333333, 0.66666667])

In [48]:
print(np.mean(scores))

0.5925925925925926


In [49]:
print(np.std(scores))

0.15438270370863952
